; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "R-SODIUM Precision TouchPad Configurator"
#define MyAppId "{EB35F096-C5E3-4621-B575-6F3858484E0A}"
#define MyAppVersion "0.0.1"
#define MyAppPublisher "R-SODIUM Technology"
#define MyAppURL "https://github.com/barryblueice/R-SODIUM-Precision-TouchPad-Configurator"
#define MyAppExeName "rsodium_touchpad.exe"
#define MyAppAssocName MyAppName + " Setup"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=D:\Documents\test\R-SODIUM-Precision-TouchPad-Configurator\LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=D:\Downloads
OutputBaseFilename=R-SODIUM.Precision.TouchPad.Configurator.Setup
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Documents\test\R-SODIUM-Precision-TouchPad-Configurator\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Documents\test\R-SODIUM-Precision-TouchPad-Configurator\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
  UninstallKey = 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppId}_is1';
  { Keep this title in sync with window.Create in windows/runner/main.cpp. }
  AppWindowTitle = 'R-SODIUM TouchPad Configurator';

function UninstallPreviousVersion(RootKey: Integer): String;
var
  UninstallCommand: String;
  ResultCode: Integer;
begin
  Result := '';
  if not RegKeyExists(RootKey, UninstallKey) then
    Exit;

  if FindWindowByWindowName(AppWindowTitle) <> 0 then
  begin
    Result := 'Please exit {#MyAppName}, then retry installation.';
    Exit;
  end;

  if not RegQueryStringValue(RootKey, UninstallKey, 'UninstallString', UninstallCommand) then
  begin
    Result := 'The previous {#MyAppName} installation has no uninstall command. Please uninstall it manually first.';
    Exit;
  end;
  if Trim(UninstallCommand) = '' then
  begin
    Result := 'The previous {#MyAppName} uninstall command is empty. Please uninstall it manually first.';
    Exit;
  end;

  Log('Uninstalling the previous {#MyAppName} installation: ' + UninstallCommand);
  { Pass the complete registered command so quoted paths and arguments are preserved. }
  if not Exec('>', UninstallCommand + ' /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /LOG',
    '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    Result := 'Could not start the previous {#MyAppName} uninstaller: ' + SysErrorMessage(ResultCode);
    Exit;
  end;
  if ResultCode <> 0 then
  begin
    Result := Format('The previous {#MyAppName} uninstall failed (exit code %d). Installation cannot continue.', [ResultCode]);
    Exit;
  end;
  if RegKeyExists(RootKey, UninstallKey) then
    Result := 'The previous {#MyAppName} installation is still registered. Please uninstall it manually before continuing.';
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
begin
  Result := '';
  { Check privileges before removing anything when switching installation scope. }
  if not IsAdminInstallMode then
  begin
    if RegKeyExists(HKLM64, UninstallKey) or RegKeyExists(HKLM32, UninstallKey) then
    begin
      Result := '{#MyAppName} is installed for all users. ' +
        'Please restart Setup and select the all-users installation mode ' +
        'so it can be uninstalled first.';
      Exit;
    end;
  end;

  { This installer only supports 64-bit Windows; also find older 32-bit records. }
  Result := UninstallPreviousVersion(HKLM64);
  if Result <> '' then Exit;
  Result := UninstallPreviousVersion(HKLM32);
  if Result <> '' then Exit;
  Result := UninstallPreviousVersion(HKCU64);
  if Result <> '' then Exit;
  Result := UninstallPreviousVersion(HKCU32);
end;
